import { jsPDF } from 'jspdf';
import { Expense } from '../stores/eventStore';

export const generateReceipt = (expense: Expense, categoryName: string) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  // Set up the document
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  
  // Add title
  doc.text('RECEIPT', 105, 20, { align: 'center' });
  
  // Add receipt date
  const receiptDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.setFontSize(10);
  doc.text(`Generated on: ${receiptDate}`, 105, 30, { align: 'center' });
  
  // Add horizontal line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 35, 190, 35);
  
  // Add expense details
  doc.setFontSize(12);
  doc.text('Expense Details', 20, 45);
  
  doc.setFontSize(10);
  doc.text(`Description: ${expense.description}`, 20, 55);
  doc.text(`Amount: $${expense.amount.toFixed(2)}`, 20, 65);
  
  const expenseDate = new Date(expense.date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  
  doc.text(`Date: ${expenseDate}`, 20, 75);
  doc.text(`Category: ${categoryName}`, 20, 85);
  
  // Add horizontal line
  doc.line(20, 95, 190, 95);
  
  // Add note
  doc.setFontSize(8);
  doc.text('This receipt was generated by Smart Event Budget Planner.', 105, 270, { align: 'center' });
  
  // Save the PDF
  doc.save(`receipt-${expense.id}.pdf`);
};